### PR TITLE
Mathvariant deprecated, use unicode for double struck characters

### PR DESCRIPTION
**Pull request by kedashoe**
Partially addresses https://github.com/runarberg/mathup/issues/70

Was looking for alternatives to asciimath and found this, seems great! Noticed the browser telling me mathvariant was deprecated so gave it a look.

Let me know what you think, wasn't sure the best place to update the code for this. I imagine eventually the tokenizer would not mention mathvariant at all, but to start this work I've left that part untouched and transformed the literal.

### CODE REVIEW

**Review by runarberg — APPROVED** [review]
This looks great. Thanks for the contribution.

**Comment by runarberg** [comment]
@kedashoe I’m actually not an expert in compiler design (this is my only compiler) but I think the transformer is the correct choice here. It feels like the correct choice to leave the source input in the AST as it allows us to additional (or different) transformations e.g. between `bb R^2` and `ℝ^2`.

There are still more variants we need to implement, but this is an excellent start. I’m also thinking about changing the behavior of the font commands before v1.0.0, such that they only affect the next identifier or number unless explicitly delimited. I’m a bit annoyed at `bb P(n)` rendering as ℙ(𝕟) instead of ℙ(n). But that change would actually be in the parser I think, and is unrelated.

Thanks again for the contribution. Lets merge this in.

**Comment by runarberg** [comment]
Released [v1.0.0-alpha.3](https://github.com/runarberg/mathup/releases/tag/v1.0.0-alpha.3)

I plan on doing a 1.0 release when fully compliant with MathML Core.

**Comment by kedashoe** [comment]
> Released v1.0.0-beta.3

Looks like there may have been an issue with the release.

`import mathup from 'mathup';` results in

```
node:internal/modules/cjs/loader:553
      throw e;
      ^

Error [ERR_INVALID_PACKAGE_TARGET]: Invalid "exports" main target "src/index.js" defined
in the package config /tmp/a/node_modules/mathup/package.json; targets must start with "./"
```
Patching `/node_modules/mathup/package.json`

`"exports": "src/index.js",` -> `"exports": "./src/index.js",`

seemed to do the trick

**Pull request merged**
